In [ ]:
bin(12)

In [ ]:
~12

In [ ]:
bin(-13)

In [ ]:
12|13

In [ ]:
12&13

In [ ]:
import math as m

In [ ]:
m.ceil(12.2)

In [ ]:
m.fabs(12.23254)  #return absolute value

In [ ]:
l=eval(input('enter expression'))
print(l)

In [ ]:
x=int(input('enter number'))
a=x%2
if a==0:
    print('it is even')
    if x>10:
        print('great')
    else:
        print('ok')
else:
    print('it is odd')

In [ ]:
x=int(input('define no'))
av=10
i=1
while i<=x:
    if i>av:
        break
    print("cotton candy")
    i+=1

In [ ]:
import math as m
for i in range(1,500):
    x=m.sqrt(i)
    if(x-m.floor(x)==0):
        print(i)

In [ ]:
for i in range(5):
    for j in range(i+1):
        print('*',end=" ")
    print()

In [ ]:
x=int(input("enter number"))
for i in range(2,x):
    if x%i==0 :
        print('non prime')
        break
else:
        print('prime')

In [ ]:
from array import *
v = array('i',[12,56,78,98,78,4,15,2,5,0])

for i in v:
    print(i)

In [ ]:
v.typecode

In [ ]:
new = array('i',[a*2 for a in v])
for i in new:
    print(i)

In [ ]:
for i in range(len(new)):
    for j in range(len(new)-1):
        if new[j]>new[j+1]:
            new[j]=new[j]^new[j+1]
            new[j+1]=new[j]^new[j+1]
            new[j]=new[j]^new[j+1]
            
for i in new:
    print(i)
            

In [ ]:
x=int(input('number'))
b=1
for i in range(1,x+1):
    b=b*i
    
print(b)
    

In [ ]:
x=array('i',[12,56,45,87,98,78])
x.index(56)

In [2]:
from numpy import *

In [3]:
a=array([1,2,3,4,5,6,8])

In [ ]:
print(a)

In [5]:
v=linspace(1,10,5)
print(v)

[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
3.25-1

2.25

In [7]:
3.25+2.25

5.5

In [10]:
v=arange(0,100,10)
print(v)

[ 0 10 20 30 40 50 60 70 80 90]


In [11]:
help('array')

Help on module array:

NAME
    array

MODULE REFERENCE
    https://docs.python.org/3.7/library/array
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array
    
    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |  
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, whi

In [14]:
import numpy as d

In [26]:
a= d.array([[1,2,3,5],[4,58,9,4]])
print(a)
print(a.ndim)
print(a.flatten())

[[ 1  2  3  5]
 [ 4 58  9  4]]
2
[ 1  2  3  5  4 58  9  4]


In [24]:
b=d.array([1,2,3])

In [25]:
print(b)

[1 2 3]


In [3]:

def fib(x):
    a=0
    b=1
    print(a)
    print(b)
    for i in range(2,x):
        c=a+b
        print(c)
        a=b
        b=c
        
x=int(input("enter number"))
fib(x)

enter number5
0
1
1
2
3


In [2]:
def fib(x):
    if x==0:
        return 1
    else:
        return x*fib(x-1)
    
x=int(input("enter number"))
print(fib(x))

enter number6
720


In [4]:
f=lambda x:x*x*8*8
x=2
print(f(x))

256


In [5]:
f=lambda a,b:a+b
a=12
b=4
print(f(a,b))

16


In [10]:
lst = [1,2,3,4,5,6,7,8,9,10,54,68,78,44,65]
def even(x):
    return x%2==0
f=list(filter(even,lst))
print(f)
    

[2, 4, 6, 8, 10, 54, 68, 78, 44]


In [12]:
d=list(filter(lambda a:a%2==0,lst))
print(d)

[2, 4, 6, 8, 10, 54, 68, 78, 44]


In [14]:
lst = [1,2,3,4,5,6,7,8,9,10,54,68,78,44,65]
f=list(filter(lambda a:a%2==0,lst))
print('f=',f)
d=list(map(lambda a:a*2,f))
print("d=",d)

f= [2, 4, 6, 8, 10, 54, 68, 78, 44]
d= [4, 8, 12, 16, 20, 108, 136, 156, 88]


In [19]:
from functools import reduce
lst = [1,2,3,4,5,6,7,8,9,10,54,68,78,44,65]
f=reduce(lambda a,b:a+b,lst)
print(f)

364


In [35]:
def div(a,b):
    print(a/b)
    
def sort(func):
    def inner(a,b):
            if a<b:
                a,b=b,a
            return func(a,b)
    return inner
div1=sort(div)
div1(1,2)

2.0


In [36]:
import import_ipynb

In [38]:
from link import *
sub(2,6)

-4


In [40]:
div(2,8)

0.25


In [41]:
sub(1,5)

-4


In [42]:
import import_ipynb

In [43]:
print(__name__)

__main__


In [46]:
a=5
a.bit_length()

3

In [47]:
help('bit_length()')

No Python documentation found for 'bit_length()'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [51]:
def add(a,b):
    print(a+b)
    
a=int(input("enter number 1"))
b=int(input("enter number 2"))

add(a,b)

enter number 11020
enter number 2255
1275


In [53]:
class dushant:
    def __init__(self,m,f):
        self.m=m
        self.f=f
        print(self.m,self.f)
        
d=dushant(12,'dushant')

12 dushant


In [57]:
class one:
    def __init__(self):
        self.name='dushant'
        self.age=18
        
    def compare(self,other):
        if self.name==other.name and self.age==other.age:
            print('they are equal')
        else:
            print('they are different')
a=one()
b=one()
a.compare(b)
a.name='dushantp'
b.age=19
a.compare(b)





they are equal
they are different


In [64]:
class car:
    wheels=8
    def __init__(self):
        self.name='dushant'
        self.age=18
    def output(self):
        print(self.name)
        print(self.age)
a=car()
b=car()
a.wheels=5
a.output()
car.wheels=5
print(b.wheels)

dushant
18
5


In [68]:
# types of methods part1

class student:
    school = 'vjti'
    
    def __init__(self,m1,m2,m3):
        
        self.m1=m1
        self.m2=m2
        self.m3=m3
        
    def avg(self):
        return (self.m1+self.m2+self.m3)/3
    
c1=student(12,56,45)
c2=student(87,98,56)

print(c1.avg())
print(c2.avg())



37.666666666666664
80.33333333333333


In [7]:
class cs:
    car=45
    
    #@classmethod
    def output(self):
        print(self.car)
        
a=cs()
print(a.car)
a.car=55
cs.car=65
a.output()
print(cs.car)


45
55
65


In [13]:
class student:
    college = 'vjti'
    @staticmethod
    def info():
        print('this is student class')
              
a=student()
a.info()

this is student class


In [22]:
class cl1:
    def __init__(self,name,id):
        self.name=name
        self.id=id
        self.lap=self.cl2()
    def show(self):
        print('id= ',self.id)
        print('name= ',self.name)
    
    class cl2:
        def __init__(self):
            self.model='dell'
            self.ram=4
        def show(self):
            print(self.model,self.ram)
            
a=cl1('dushant',18)
a.show()
a.lap.show()

id=  18
name=  dushant
dell 4


In [28]:
class a:
    def __init__(self):
        print('constructor of a is called')
class b(a):
    @staticmethod
    def f():
        print('my job has done')
    @staticmethod
    def a():
        print('kd kn')

x=b()
x.f()
x.a()

constructor of a is called
my job has done
kd kn


In [30]:

class A:
    def __init__(self):
        print('class a is called')
class B(A):
    def __init__(self):
        print('class b is called')
        super().__init__()
x=B()

class b is called
class a is called


In [35]:

class A:
    def __init__(self):
        print('class a is called')
        
    def test(self):
        print('test a')
class B:
    def __init__(self):
        print('class b is called')
        
    def test(self):
        print('test b')
        
class C(A,B):
    def __init__(self):
        print('class c is called')
        super().__init__()
d=C()
d.test()

class c is called
class a is called
test a


In [37]:
class a:
    def execute(self):
        print('running')
        
class b:
    def execute(self):
        print('compiling')
        
class run(a,b):
    def __init__(self,ide):
        ide.execute(self)
    
x=run(a)
q=run(b)

running
compiling


In [43]:
class A:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
        
    def __add__(self,other):
        p=self.m1+other.m1
        q=self.m2+other.m2
        return p,q
    def __sub__(self,other):
        p=self.m1-other.m1
        q=self.m2-other.m2
        return p,q
    
p=A(12,89)
q=A(45,78)
i=p+q
print("sum=",i)
r=p-q
print('sub=',r)
        

sum= (57, 167)
sub= (-33, 11)


In [42]:
help('def')

Function definitions
********************

A function definition defines a user-defined function object (see
section The standard type hierarchy):

   funcdef                 ::= [decorators] "def" funcname "(" [parameter_list] ")"
               ["->" expression] ":" suite
   decorators              ::= decorator+
   decorator               ::= "@" dotted_name ["(" [argument_list [","]] ")"] NEWLINE
   dotted_name             ::= identifier ("." identifier)*
   parameter_list          ::= defparameter ("," defparameter)* ["," [parameter_list_starargs]]
                      | parameter_list_starargs
   parameter_list_starargs ::= "*" [parameter] ("," defparameter)* ["," ["**" parameter [","]]]
                               | "**" parameter [","]
   parameter               ::= identifier [":" expression]
   defparameter            ::= parameter ["=" expression]
   funcname                ::= identifier

A function definition is an executable statement.  Its execution binds
the functio

In [44]:
class a:
    def __init__(self):
        self.m1=int(input('enter sub1 marks'))
        
        self.m2=int(input('enter sub2 marks'))
    def __gt__(self,other):
        r1=self.m1+self.m2
        r2=other.m1+other.m2
        if r1>r2:
            return True
        else:
            return False
p=a()
q=a()
if p>q:
    print('p wins')
else:
    print('q wins')
        

enter sub1 marks12
enter sub2 marks23
enter sub1 marks45
enter sub2 marks45
q wins


In [46]:
class a:
    def __init__(self):
        self.m1=int(input('enter sub1 marks'))
        self.m2=int(input('enter sub2 marks'))
    def __str__(self):
        return self.m1,self.m2
q=a()
print(q.__str__())

enter sub1 marks45
enter sub2 marks65
(45, 65)


In [49]:
class a:
    def __init__(self):
        self.m1=int(input('enter sub1 marks'))
        self.m2=int(input('enter sub2 marks'))
    def __str__(self):
        return '{},{}'.format(self.m1,self.m2)
q=a()
print(q.__str__())
print(q)

enter sub1 marks45
enter sub2 marks65
45,65
45,65


In [56]:
class sum:
    def __init__(self):
        self.a=int(input('num1'))
        self.b=int(input('num1'))
        self.c=int(input('num1'))
    def add(self,self.a=None,self.b=None,self.c=None):
        if self.a!=None and self.b!=None and self.c!=None:
            s=self.a+self.b+self.c
        elif a!=None and b!=None:
            s=self.a+self.b
        else:
            s=self.a
        return s
a=sum()
print(a.add(a,b))
            

SyntaxError: invalid syntax (<ipython-input-56-87d09b5c2bc6>, line 6)

In [60]:
class sum:
    def __init__(self):
        a=int(input('1'))
        print(a)
    def s(self):
        print(a)
q=sum()

145
45
None


In [78]:
from abc import ABC,abstractmethod
class A(ABC):
    @abstractmethod
    def show(self):
        print('asd')
class B(A):
    def show(self):
        print('151')
q=B()


In [86]:
lst = [12,45,98,79,84,96,45]
it=iter(lst)
print(it.__next__())
print(it.__next__())
print(next(it))


12
45
98


In [93]:
class iteration:
    def  __init__(self):
        self.no=1
    def __iter__(self):
        return self
    def __next__(self):
        if self.no <10:
            v=self.no
            self.no+=1
            return v
        else: 
            raise stopped
        
        
q=iteration()
for i in q:
    print(i)

1
2
3
4
5
6
7
8
9


NameError: name 'stopped' is not defined

In [95]:
def y():
    yield 1
    yield 2
    yield 245
    yield 24
    yield 223
q=y()
for i in q:
    print(i)

1
2
245
24
223


In [97]:
def square():
    n=1
    while n<10:
        q=n*n
        yield q
        n=n+1
w=square()
for i in w:
    print(i)

1
4
9
16
25
36
49
64
81


In [100]:
a=int(input('num1'))
b=int(input('num2'))
try:
    print(a/b)
except Exception as a:
    print('error',a)

num12
num20
error division by zero
